// <auto-generated />
namespace Poultry.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class new1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new1));
        
        string IMigrationMetadata.Id
        {
            get { return "201411230649574_new1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
